# Generated by Django 5.0.3 on 2024-05-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_promotion_product_promotiona_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='promotiona_price',
            new_name='promotion_price',
        ),
    ]
