# Generated by Django 5.0.3 on 2024-05-04 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_promotion_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=5000, null=True)),
                ('slogan', models.CharField(max_length=2048, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores_images')),
                ('deposit_account', models.CharField(default='0000 0000 0000 0000', max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
