# Generated by Django 5.0.3 on 2024-05-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
