# Generated by Django 5.0.3 on 2024-05-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
