# Generated by Django 5.0.3 on 2024-05-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_delete_tansaction'),
        ('store', '0012_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cart'),
        ),
    ]
