# Generated by Django 5.0.3 on 2024-05-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_cart'),
        ('store', '0012_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
