# Generated by Django 5.0.3 on 2024-05-16 23:51

import chargily_epay_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_order_the_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargilyPayment',
            fields=[
                ('invoice_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=64)),
                ('comment', models.TextField()),
                ('discount', models.FloatField(blank=True, default=0, max_length=2)),
                ('mode', models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25)),
                ('status', models.CharField(choices=[('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('paid', 'PAID'), ('expired', 'EXPIRED'), ('failed', 'FAILED')], default='progress', max_length=25)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=(chargily_epay_django.models.FakePaymentMixin, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to be sent', ' to be sent'), ('sent', 'order sent'), ('CANCELED', 'order canceled')], default='to be sent', max_length=50),
        ),
    ]
