# Generated by Django 5.0.3 on 2024-05-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='more_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('paid', 'PAID'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
    ]
