# Generated by Django 5.0.3 on 2024-05-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transaction_more_info_alter_chargilypayment_mode_and_more'),
        ('store', '0012_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('progress', 'IN PROGRESS'), ('failed', 'FAILED'), ('canceled', 'CANCELED'), ('paid', 'PAID'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
    ]
