# Generated by Django 5.0.3 on 2024-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_order_item_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('expired', 'EXPIRED'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED'), ('paid', 'PAID')], default='progress', max_length=25),
        ),
    ]
