# Generated by Django 5.0.3 on 2024-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('paid', 'PAID'), ('expired', 'EXPIRED'), ('progress', 'IN PROGRESS'), ('canceled', 'CANCELED')], default='progress', max_length=25),
        ),
    ]
