# Generated by Django 5.0.3 on 2024-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('progress', 'IN PROGRESS'), ('failed', 'FAILED'), ('paid', 'PAID'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED')], default='progress', max_length=25),
        ),
    ]
