# Generated by Django 5.0.3 on 2024-05-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED')], default='progress', max_length=25),
        ),
    ]
