# Generated by Django 5.0.3 on 2024-05-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_chargilypayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('failed', 'FAILED'), ('progress', 'IN PROGRESS'), ('expired', 'EXPIRED'), ('paid', 'PAID')], default='progress', max_length=25),
        ),
    ]
