# Generated by Django 5.0.3 on 2024-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED'), ('paid', 'PAID')], default='progress', max_length=25),
        ),
    ]
