# Generated by Django 5.0.3 on 2024-05-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('progress', 'IN PROGRESS'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
