# Generated by Django 5.0.3 on 2024-05-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_chargilypayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('canceled', 'CANCELED'), ('failed', 'FAILED'), ('progress', 'IN PROGRESS'), ('paid', 'PAID'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.FloatField(),
        ),
    ]
