# Generated by Django 5.0.3 on 2024-05-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_chargilypayment_status_alter_transaction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('expired', 'EXPIRED'), ('failed', 'FAILED')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
