# Generated by Django 5.0.3 on 2024-05-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_chargilypayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('progress', 'IN PROGRESS'), ('failed', 'FAILED')], default='progress', max_length=25),
        ),
    ]
