# Generated by Django 5.0.3 on 2024-05-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_chargilypayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('progress', 'IN PROGRESS'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('to be sent', ' to be sent'), ('sent', 'sent'), ('canceled', 'canceled')], default='to be sent', max_length=50),
        ),
    ]
