# Generated by Django 5.0.3 on 2024-05-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_chargilypayment_mode_and_more'),
        ('store', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('canceled', 'CANCELED'), ('paid', 'PAID'), ('progress', 'IN PROGRESS'), ('expired', 'EXPIRED')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
