# Generated by Django 5.0.3 on 2024-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_chargilypayment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargilypayment',
            name='mode',
            field=models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='chargilypayment',
            name='status',
            field=models.CharField(choices=[('failed', 'FAILED'), ('paid', 'PAID'), ('canceled', 'CANCELED'), ('expired', 'EXPIRED'), ('progress', 'IN PROGRESS')], default='progress', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('to be sent', ' to be sent'), ('sent', 'sent'), ('canceled', 'canceled')], default='waiting', max_length=50),
        ),
    ]
