# Generated by Django 5.0.3 on 2024-03-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_specific_property', models.CharField(max_length=100)),
                ('lives_in', models.CharField(default='Algeria', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_specific_property', models.CharField(max_length=100)),
                ('store_deposit_account', models.CharField(default='0000 0000 0000 0000', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
