# Generated by Django 5.0.3 on 2024-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_info',
            name='store',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
