# Generated by Django 5.0.3 on 2024-05-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_vendor_info_store_deposit_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_info',
            old_name='store',
            new_name='bio',
        ),
    ]
