# Generated by Django 5.0.3 on 2024-05-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='customer_specific_property',
        ),
        migrations.RemoveField(
            model_name='vendor_info',
            name='vendor_specific_property',
        ),
    ]
