# Generated by Django 5.0.3 on 2024-05-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_info_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='avatar',
            new_name='image',
        ),
    ]
