# Generated by Django 5.0.3 on 2024-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_avatar_customer_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
